# Generated by Django 3.2.4 on 2021-06-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='Role',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
