# Generated by Django 3.2.4 on 2021-06-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0002_login_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='EmpName',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
