# Generated by Django 3.2.4 on 2021-06-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0003_alter_login_empname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_Name', models.CharField(max_length=80)),
                ('Employee_Id', models.CharField(max_length=80)),
                ('Employee_Designation', models.CharField(max_length=80)),
                ('Date', models.DateField(blank=True, null=True)),
                ('Type_of_Reimbursement', models.CharField(choices=[('Food', 'Food'), ('Travelling', 'Travelling'), ('Medical', 'Medical'), ('Internet', 'Internet'), ('Other', 'Other')], default='New Type_of_Reimbursement=models', max_length=70)),
                ('Description', models.TextField(max_length=400)),
                ('Upload_Bill', models.ImageField(blank='True', null='True', upload_to='pics')),
                ('Expense_Ammount_In_Rs', models.IntegerField()),
            ],
        ),
    ]
