# Generated by Django 3.2.4 on 2021-06-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0004_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Status',
            field=models.BooleanField(default=False),
        ),
    ]
