# Generated by Django 3.2.4 on 2021-06-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0006_alter_employee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
